from __future__ import annotations

from typing import Any


DEFAULT_PLAYBOOKS: list[dict[str, Any]] = [
    {
        "code": "recovery_supply_company_v1",
        "title": "Взыскание задолженности по поставке (юрлицо)",
        "contract_type": "supply",
        "debtor_type": "company",
        "description": "Базовый recovery playbook для поставки и юрлица.",
        "steps": [
            {
                "step_code": "payment_due_notice",
                "title": "Напоминание о наступлении срока оплаты",
                "sequence_no": 10,
                "step_type": "action",
                "action_code": "send_payment_due_notice",
                "document_code": "payment_due_notice",
                "is_manual": True,
                "is_blocking": True,
                "waiting_rule_code": None,
                "eligibility_expr": "case_status in ['draft', 'overdue']",
            },
            {
                "step_code": "debt_notice",
                "title": "Уведомление о задолженности",
                "sequence_no": 20,
                "step_type": "action",
                "action_code": "send_debt_notice",
                "document_code": "debt_notice",
                "is_manual": True,
                "is_blocking": True,
                "waiting_rule_code": "wait_after_due_notice",
                "eligibility_expr": "payment_due_notice_sent == True and debt_notice_sent != True",
            },
            {
                "step_code": "pretrial_claim",
                "title": "Досудебная претензия",
                "sequence_no": 30,
                "step_type": "action",
                "action_code": "send_pretension",
                "document_code": "pretension",
                "is_manual": True,
                "is_blocking": True,
                "waiting_rule_code": "wait_after_debt_notice",
                "eligibility_expr": "debt_notice_sent == True and pretrial_sent != True",
            },
            {
                "step_code": "court_filing",
                "title": "Подача в суд",
                "sequence_no": 40,
                "step_type": "external_action",
                "action_code": "submit_to_court",
                "document_code": "lawsuit",
                "is_manual": True,
                "is_blocking": True,
                "waiting_rule_code": "wait_after_pretension",
                "eligibility_expr": "pretrial_sent == True and court_filed != True",
            },
            {
                "step_code": "fssp_submission",
                "title": "Направление в ФССП",
                "sequence_no": 50,
                "step_type": "external_action",
                "action_code": "send_to_fssp",
                "document_code": "fssp_application",
                "is_manual": True,
                "is_blocking": False,
                "waiting_rule_code": "wait_after_court_result",
                "eligibility_expr": "court_filed == True and enforcement_started != True",
            },
        ],
    },
    {
        "code": "recovery_rent_company_v1",
        "title": "Взыскание задолженности по аренде (юрлицо)",
        "contract_type": "rent",
        "debtor_type": "company",
        "description": "Базовый recovery playbook для аренды и юрлица.",
        "steps": [
            {
                "step_code": "payment_due_notice",
                "title": "Напоминание о наступлении срока оплаты",
                "sequence_no": 10,
                "step_type": "action",
                "action_code": "send_payment_due_notice",
                "document_code": "payment_due_notice",
                "is_manual": True,
                "is_blocking": True,
                "waiting_rule_code": None,
                "eligibility_expr": "case_status in ['draft', 'overdue']",
            },
            {
                "step_code": "debt_notice",
                "title": "Уведомление о задолженности",
                "sequence_no": 20,
                "step_type": "action",
                "action_code": "send_debt_notice",
                "document_code": "debt_notice",
                "is_manual": True,
                "is_blocking": True,
                "waiting_rule_code": "wait_after_due_notice",
                "eligibility_expr": "payment_due_notice_sent == True and debt_notice_sent != True",
            },
            {
                "step_code": "pretrial_claim",
                "title": "Досудебная претензия",
                "sequence_no": 30,
                "step_type": "action",
                "action_code": "send_pretension",
                "document_code": "pretension",
                "is_manual": True,
                "is_blocking": True,
                "waiting_rule_code": "wait_after_debt_notice",
                "eligibility_expr": "debt_notice_sent == True and pretrial_sent != True",
            },
            {
                "step_code": "court_filing",
                "title": "Подача в суд",
                "sequence_no": 40,
                "step_type": "external_action",
                "action_code": "submit_to_court",
                "document_code": "lawsuit",
                "is_manual": True,
                "is_blocking": True,
                "waiting_rule_code": "wait_after_pretension",
                "eligibility_expr": "pretrial_sent == True and court_filed != True",
            },
        ],
    },
]


def list_default_playbooks() -> list[dict[str, Any]]:
    return DEFAULT_PLAYBOOKS